services:
  webserver:
    image: nginx:latest
    container_name: webserver
    env_file:
      - .env
    volumes:
      - ./dist:/usr/share/nginx/html/to-dog-list
      - ./public:/usr/share/nginx/html/to-dog-list/public
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

networks:
  defaults: 
    name: to-dog-list-network

